language: node_js
node_js:
  - "8.4"
install:
  - npm config set spin=false
  - npm install -g npm@5.2
  - npm install -g coveralls
  - npm install
os:
  - linux
branches:
  only:
  - publish
script:
  - npm test
  - npm run coverage
  - coveralls < ./lcov.info || true # if coveralls doesn't have it covered
# Allow Travis tests to run in containers.
sudo: false
