# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: IfNotPresent
service:
  name: node
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
resources:
  requests:
    cpu: 200m
    memory: 512Mi

ingress:
  enabled: false
env:
  CONNECTION_ID: v1
  LOG_LEVEL: info
  HEMERA_LOG_LEVEL: info
external:
  name: idestack
  service: 
    mongodb:
      generateEnv: true
      enabled: false
      serviceName: mongo-ha-mongodb-replicaset.main-system.svc.cluster.local
      port: 27017
      dbname: idestack
    nats:
      generateEnv: true
      enabled: false
      serviceName: microstack-nats-stable-client.main-system.svc.cluster.local
      user: ruser
      password: "T0pS3cr3t"
      port: 4222
    zipkin:
      generateEnv: true
      enabled: false
      serviceName: microstack-zipkin.main-system.svc.cluster.local
      port: 9411
    redis:
      generateEnv: true
      enabled: false
      serviceName: microstack-redis-ha-haproxy.main-system.svc.cluster.local
      port: 6379

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60