{{- if .Values.external.service.mongodb.enabled  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongodb.fullname" . }}
  namespace: "{{ .Release.Namespace }}"
  labels:
{{ include "labels.standard" . | indent 4 }}
    component: {{ template "mongodb.fullname" . }}
spec:
  type: ExternalName
  externalName: {{ .Values.external.service.mongodb.serviceName | quote }}
  ports:
  - port: {{ .Values.external.service.mongodb.port }}
{{- end -}}
