# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: IfNotPresent
service:
  name: node
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: false
env:
  CONNECTION_ID: v1
  BRIGADE_PROJECT_ID: "brigade-fc500e5f406ddcff3c0cc1e1e39ecfe605e4c1e34d45b36ce15d6c"
  LOG_LEVEL: info
  HEMERA_LOG_LEVEL: info
