# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: IfNotPresent
service:
  name: node
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: false
env:
  CONNECTION_ID: v1
  BRIGADE_PROJECT_ID: "brigade-fc500e5f406ddcff3c0cc1e1e39ecfe605e4c1e34d45b36ce15d6c"
  LOG_LEVEL: info
  HEMERA_LOG_LEVEL: info
  CONNECTION_ID: v1
  NATS_URL: "nats://microstack-nats.main-system.svc.cluster.local:4222"
  NATS_USER: "ruser"
  NATS_PW: "T0pS3cr3t"
  REDIS_URL: "redis://microstack-redis-cache.main-system.svc.cluster.local:6379"
  MONGO_URL: "mongodb://microstack-mongodb.main-system.svc.cluster.local:27017/idestack"
  ZIPKIN_URL: "microstack-zipkin.main-system.svc.cluster.local"
  ZIPKIN_PORT: "9411"
external:
  service:
    mongodb:
      enabled: false
      serviceName: microstack-mongodb.main-system.svc.cluster.local
      port: 27017
      dbname: idestack
    nats:
      enabled: false
      serviceName: microstack-nats.main-system.svc.cluster.local
      user: ruser
      password: "T0pS3cr3t"
      port: 4222
    zipkin:
      enabled: false
      serviceName: microstack-zipkin.main-system.svc.cluster.local
      port: 9411
    redis:
      enabled: false
      serviceName: microstack-redis-cache.main-system.svc.cluster.local
      port: 6379
