name: Prepare
description: Prepares the repo for a typical CI job

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: "yarn"
    - run: yarn install
      shell: bash
